# Add configuration values here, as shown below.
#

S3_BUCKET_NAME: "instasnap-next"
AWS_ACCESS_KEY_ID: "AAKIAI2UORRVV36XXMM3Q"
AWS_SECRET_ACCESS_KEY: "NdMbhffuKZIRghYeb61vkr7mcblWj24Wyb0ptzjH"
AWS_REGION: "us-west-2"
